#include <gtest/gtest.h>

#include <array>
#include <fstream>
#include <sstream>

#include "../album.h"
#include "../cue.h"
#include "../multitrack_strategy.h"
#include <nlohmann/json.hpp>

using namespace std::string_view_literals;

namespace {
const auto strategy = multitrack_strategy::single();

template <std::size_t N>
void test_cue_generation(
    const std::array<std::vector<std::string_view>, N>& cues) {
  const auto basepath = std::filesystem::path{
      ::testing::UnitTest::GetInstance()->current_test_info()->name()};

  auto jsonpath =
      std::filesystem::path{"test"} / std::filesystem::path{"data"} / basepath;
  jsonpath.replace_extension(".json");
  std::ifstream f(jsonpath, std::ios::in);
  nlohmann::json j;
  f >> j;

  const auto album = Album::from_json(j, *strategy, *strategy);

  std::vector<std::shared_ptr<std::iostream>> streams;
  streams.reserve(N);

  std::vector<std::filesystem::path> expected_cue_paths;
  if (album.discs.size() == 1) {
    auto path = basepath;
    path.replace_extension(".cue");
    expected_cue_paths.push_back(path);
  } else {
    for (unsigned int d = 0; d < album.discs.size(); ++d) {
      auto s = basepath.filename().string();
      s.append("-");
      s.append(std::to_string(d + 1));
      auto path = basepath;
      path.replace_filename(s);
      path.replace_extension(".cue");
      expected_cue_paths.push_back(path);
    }
  }

  auto wavpath = basepath;
  wavpath.replace_extension(".wav");

  cue::generate(album, wavpath, [&](auto& cue_path) {
    auto stream = std::make_shared<std::stringstream>();
    streams.push_back(stream);
    EXPECT_EQ(cue_path, expected_cue_paths.at(streams.size() - 1));
    return stream;
  });

  ASSERT_EQ(streams.size(), cues.size());
  for (unsigned int cue_idx = 0; cue_idx < N; ++cue_idx) {
    auto& stream = *(streams[cue_idx]);
    auto& expected = cues[cue_idx];

    unsigned int line_idx;
    std::string line;
    for (line_idx = 0; std::getline(stream, line); ++line_idx) {
      if (line.find("REM COMMENT \"DCue") == 0) {
        continue;
      }
      ASSERT_EQ(line.back(), '\r');
      line.pop_back();
      ASSERT_EQ(line, expected[line_idx]);
    }
    std::getline(stream, line);
    ASSERT_TRUE(line.empty()) << "last line not empty";
    ASSERT_TRUE(stream.eof());
    ASSERT_EQ(line_idx, expected.size());
  }
}
}

TEST(CueGeneration, m218406) {
  const std::array<std::vector<std::string_view>, 3> cue = {
      {{R"cue(REM GENRE Hardcore)cue"sv,
        R"cue(REM DATE 2006)cue"sv,
        R"cue(REM COMMENT "DCue v1.4dev")cue"sv,
        R"cue(PERFORMER "Various")cue"sv,
        R"cue(TITLE "Clubland X-Treme Hardcore 3")cue"sv,
        R"cue(FILE "m218406.wav" WAVE)cue"sv,
        R"cue(	TRACK 01 AUDIO)cue"sv,
        R"cue(		TITLE "Castles In The Sky (DS Remix)")cue"sv,
        R"cue(		PERFORMER "Liz Kay")cue"sv,
        R"cue(		INDEX 01 00:00:00)cue"sv,
        R"cue(	TRACK 02 AUDIO)cue"sv,
        R"cue(		TITLE "Lost The Plot")cue"sv,
        R"cue(		PERFORMER "Darren Styles Feat. Wayne G")cue"sv,
        R"cue(		INDEX 01 05:18:00)cue"sv,
        R"cue(	TRACK 03 AUDIO)cue"sv,
        R"cue(		TITLE "Piece Of Heaven")cue"sv,
        R"cue(		PERFORMER "Wave")cue"sv,
        R"cue(		INDEX 01 08:28:00)cue"sv,
        R"cue(	TRACK 04 AUDIO)cue"sv,
        R"cue(		TITLE "Here Come The Drums")cue"sv,
        R"cue(		PERFORMER "United In Dance")cue"sv,
        R"cue(		INDEX 01 12:22:00)cue"sv,
        R"cue(	TRACK 05 AUDIO)cue"sv,
        R"cue(		TITLE "Everytime We Touch (Styles & Breeze Remix)")cue"sv,
        R"cue(		PERFORMER "Cascada")cue"sv,
        R"cue(		INDEX 01 15:37:00)cue"sv,
        R"cue(	TRACK 06 AUDIO)cue"sv,
        R"cue(		TITLE "I Say I Love You")cue"sv,
        R"cue(		PERFORMER "Darren Styles & Francis Hill")cue"sv,
        R"cue(		INDEX 01 18:58:00)cue"sv,
        R"cue(	TRACK 07 AUDIO)cue"sv,
        R"cue(		TITLE "Nobody Likes The Records")cue"sv,
        R"cue(		PERFORMER "Dougal & Gammer")cue"sv,
        R"cue(		INDEX 01 23:27:00)cue"sv,
        R"cue(	TRACK 08 AUDIO)cue"sv,
        R"cue(		TITLE "Skydivin (Vocal Mix)")cue"sv,
        R"cue(		PERFORMER "Darren Styles")cue"sv,
        R"cue(		INDEX 01 27:33:00)cue"sv,
        R"cue(	TRACK 09 AUDIO)cue"sv,
        R"cue(		TITLE "Face Down Ass Up (DS Remix)")cue"sv,
        R"cue(		PERFORMER "Deja Vu")cue"sv,
        R"cue(		INDEX 01 32:02:00)cue"sv,
        R"cue(	TRACK 10 AUDIO)cue"sv,
        R"cue(		TITLE "Only You (Re-Con Remix)")cue"sv,
        R"cue(		PERFORMER "Hyperlogic")cue"sv,
        R"cue(		INDEX 01 35:45:00)cue"sv,
        R"cue(	TRACK 11 AUDIO)cue"sv,
        R"cue(		TITLE "Save Me (Re-Con Remix)")cue"sv,
        R"cue(		PERFORMER "Darren Styles")cue"sv,
        R"cue(		INDEX 01 40:13:00)cue"sv,
        R"cue(	TRACK 12 AUDIO)cue"sv,
        R"cue(		TITLE "Be With You")cue"sv,
        R"cue(		PERFORMER "Sy & Unknown Feat. Lou Lou")cue"sv,
        R"cue(		INDEX 01 43:55:00)cue"sv,
        R"cue(	TRACK 13 AUDIO)cue"sv,
        R"cue(		TITLE "Sure Feels Good")cue"sv,
        R"cue(		PERFORMER "Styles & Re-Con")cue"sv,
        R"cue(		INDEX 01 47:45:00)cue"sv,
        R"cue(	TRACK 14 AUDIO)cue"sv,
        R"cue(		TITLE "Do You Want Me Honey")cue"sv,
        R"cue(		PERFORMER "Styles & Breeze")cue"sv,
        R"cue(		INDEX 01 52:58:00)cue"sv,
        R"cue(	TRACK 15 AUDIO)cue"sv,
        R"cue(		TITLE "Silver Water (DS Remix)")cue"sv,
        R"cue(		PERFORMER "Vince Nysse & N J Hinton")cue"sv,
        R"cue(		INDEX 01 56:44:00)cue"sv,
        R"cue(	TRACK 16 AUDIO)cue"sv,
        R"cue(		TITLE "Boom Daka")cue"sv,
        R"cue(		PERFORMER "United In Dance")cue"sv,
        R"cue(		INDEX 01 61:04:00)cue"sv,
        R"cue(	TRACK 17 AUDIO)cue"sv,
        R"cue(		TITLE "Make This Happen")cue"sv,
        R"cue(		PERFORMER "Metro")cue"sv,
        R"cue(		INDEX 01 64:47:00)cue"sv},
       {R"cue(REM GENRE Hardcore)cue"sv,
        R"cue(REM DATE 2006)cue"sv,
        R"cue(REM COMMENT "DCue v1.4dev")cue"sv,
        R"cue(PERFORMER "Various")cue"sv,
        R"cue(TITLE "Clubland X-Treme Hardcore 3")cue"sv,
        R"cue(FILE "m218406.wav" WAVE)cue"sv,
        R"cue(	TRACK 01 AUDIO)cue"sv,
        R"cue(		TITLE "All About")cue"sv,
        R"cue(		PERFORMER "MC Storm, Flyin' & Sparky")cue"sv,
        R"cue(		INDEX 01 00:00:00)cue"sv,
        R"cue(	TRACK 02 AUDIO)cue"sv,
        R"cue(		TITLE "My Direction (Xtreme Edit)")cue"sv,
        R"cue(		PERFORMER "D-Code Feat. Emma")cue"sv,
        R"cue(		INDEX 01 04:08:00)cue"sv,
        R"cue(	TRACK 03 AUDIO)cue"sv,
        R"cue(		TITLE "Hardcore DJ (Re-Con Remix)")cue"sv,
        R"cue(		PERFORMER "Breeze")cue"sv,
        R"cue(		INDEX 01 08:39:00)cue"sv,
        R"cue(	TRACK 04 AUDIO)cue"sv,
        R"cue(		TITLE "When Love Becomes A Lie (Breeze Remix)")cue"sv,
        R"cue(		PERFORMER "Liz Kay")cue"sv,
        R"cue(		INDEX 01 12:00:00)cue"sv,
        R"cue(	TRACK 05 AUDIO)cue"sv,
        R"cue(		TITLE "Only If")cue"sv,
        R"cue(		PERFORMER "Breeze & Re-Con")cue"sv,
        R"cue(		INDEX 01 15:43:00)cue"sv,
        R"cue(	TRACK 06 AUDIO)cue"sv,
        R"cue(		TITLE "Truly, Madly, Deeply (Styles & Breeze Remix)")cue"sv,
        R"cue(		PERFORMER "Cascada")cue"sv,
        R"cue(		INDEX 01 19:03:00)cue"sv,
        R"cue(	TRACK 07 AUDIO)cue"sv,
        R"cue(		TITLE "Never Be Alone")cue"sv,
        R"cue(		PERFORMER "Breeze & Euphony")cue"sv,
        R"cue(		INDEX 01 21:30:00)cue"sv,
        R"cue(	TRACK 08 AUDIO)cue"sv,
        R"cue(		TITLE "Yeah Yeah (Dougal & Gammer \"The Beat's The Bass\" Remix)")cue"sv,
        R"cue(		PERFORMER "Bodyrox")cue"sv,
        R"cue(		INDEX 01 26:09:00)cue"sv,
        R"cue(	TRACK 09 AUDIO)cue"sv,
        R"cue(		TITLE "Gotta Believe (Re-Con Remix)")cue"sv,
        R"cue(		PERFORMER "Ramos, Supreme & Sunset Regime")cue"sv,
        R"cue(		INDEX 01 28:57:00)cue"sv,
        R"cue(	TRACK 10 AUDIO)cue"sv,
        R"cue(		TITLE "Rise Again")cue"sv,
        R"cue(		PERFORMER "Breeze vs. Lost Witness")cue"sv,
        R"cue(		INDEX 01 33:36:00)cue"sv,
        R"cue(	TRACK 11 AUDIO)cue"sv,
        R"cue(		TITLE "Crash")cue"sv,
        R"cue(		PERFORMER "SHM & Scottie B")cue"sv,
        R"cue(		INDEX 01 38:15:00)cue"sv,
        R"cue(	TRACK 12 AUDIO)cue"sv,
        R"cue(		TITLE "Dirty")cue"sv,
        R"cue(		PERFORMER "Breeze & UFO")cue"sv,
        R"cue(		INDEX 01 43:05:00)cue"sv,
        R"cue(	TRACK 13 AUDIO)cue"sv,
        R"cue(		TITLE "Touch The Sky")cue"sv,
        R"cue(		PERFORMER "Sy & Unknown Feat. Lou Lou")cue"sv,
        R"cue(		INDEX 01 46:18:00)cue"sv,
        R"cue(	TRACK 14 AUDIO)cue"sv,
        R"cue(		TITLE "Love You For A Lifetime")cue"sv,
        R"cue(		PERFORMER "Breeze & Re-Con")cue"sv,
        R"cue(		INDEX 01 51:07:00)cue"sv,
        R"cue(	TRACK 15 AUDIO)cue"sv,
        R"cue(		TITLE "Walking In The Rain (Styles & Breeze Remix)")cue"sv,
        R"cue(		PERFORMER "Sublime")cue"sv,
        R"cue(		INDEX 01 54:29:00)cue"sv,
        R"cue(	TRACK 16 AUDIO)cue"sv,
        R"cue(		TITLE "Come On")cue"sv,
        R"cue(		PERFORMER "Styles & Breeze")cue"sv,
        R"cue(		INDEX 01 57:50:00)cue"sv,
        R"cue(	TRACK 17 AUDIO)cue"sv,
        R"cue(		TITLE "Good To Me")cue"sv,
        R"cue(		PERFORMER "Re-Con & Squad-E")cue"sv,
        R"cue(		INDEX 01 61:46:00)cue"sv,
        R"cue(	TRACK 18 AUDIO)cue"sv,
        R"cue(		TITLE "Let Me Fly (Jamie Ritmen Remix)")cue"sv,
        R"cue(		PERFORMER "Infextious")cue"sv,
        R"cue(		INDEX 01 66:25:00)cue"sv},
       {
           R"cue(REM GENRE Hardcore)cue"sv,
           R"cue(REM DATE 2006)cue"sv,
           R"cue(REM COMMENT "DCue v1.4dev")cue"sv,
           R"cue(PERFORMER "Various")cue"sv,
           R"cue(TITLE "Clubland X-Treme Hardcore 3")cue"sv,
           R"cue(FILE "m218406.wav" WAVE)cue"sv,
           R"cue(	TRACK 01 AUDIO)cue"sv,
           R"cue(		TITLE "Untouchable (Hixxy & Squad-E Remix)")cue"sv,
           R"cue(		PERFORMER "Squad-E & Chris Henry")cue"sv,
           R"cue(		INDEX 01 00:00:00)cue"sv,
           R"cue(	TRACK 02 AUDIO)cue"sv,
           R"cue(		TITLE "Take Me With You")cue"sv,
           R"cue(		PERFORMER "Hixxy")cue"sv,
           R"cue(		INDEX 01 04:28:00)cue"sv,
           R"cue(	TRACK 03 AUDIO)cue"sv,
           R"cue(		TITLE "Freaks")cue"sv,
           R"cue(		PERFORMER "Hixxy, Sy & Unknown")cue"sv,
           R"cue(		INDEX 01 09:10:00)cue"sv,
           R"cue(	TRACK 04 AUDIO)cue"sv,
           R"cue(		TITLE "Overload (Hixxy & Re-Con Remix)")cue"sv,
           R"cue(		PERFORMER "VooDoo & Serano")cue"sv,
           R"cue(		INDEX 01 13:30:00)cue"sv,
           R"cue(	TRACK 05 AUDIO)cue"sv,
           R"cue(		TITLE "Beat Drop")cue"sv,
           R"cue(		PERFORMER "Hixxy & Squad-E")cue"sv,
           R"cue(		INDEX 01 18:55:00)cue"sv,
           R"cue(	TRACK 06 AUDIO)cue"sv,
           R"cue(		TITLE "More & More (Sy & Unknown Remix)")cue"sv,
           R"cue(		PERFORMER "Hixxy")cue"sv,
           R"cue(		INDEX 01 22:53:00)cue"sv,
           R"cue(	TRACK 07 AUDIO)cue"sv,
           R"cue(		TITLE "Come Alive")cue"sv,
           R"cue(		PERFORMER "Hixxy & Re-Con")cue"sv,
           R"cue(		INDEX 01 27:13:00)cue"sv,
           R"cue(	TRACK 08 AUDIO)cue"sv,
           R"cue(		TITLE "Hot Looking Babes")cue"sv,
           R"cue(		PERFORMER "Hixxy & Dougal & Gammer")cue"sv,
           R"cue(		INDEX 01 31:01:00)cue"sv,
           R"cue(	TRACK 09 AUDIO)cue"sv,
           R"cue(		TITLE "Forever Young (Hixxy Remix)")cue"sv,
           R"cue(		PERFORMER "Anti-Social")cue"sv,
           R"cue(		INDEX 01 34:49:00)cue"sv,
           R"cue(	TRACK 10 AUDIO)cue"sv,
           R"cue(		TITLE "First Time Meet Up")cue"sv,
           R"cue(		PERFORMER "Hixxy, Sy & Unknown")cue"sv,
           R"cue(		INDEX 01 39:09:00)cue"sv,
           R"cue(	TRACK 11 AUDIO)cue"sv,
           R"cue(		TITLE "Power Of Love")cue"sv,
           R"cue(		PERFORMER "Hixxy & Re-Con")cue"sv,
           R"cue(		INDEX 01 44:12:00)cue"sv,
           R"cue(	TRACK 12 AUDIO)cue"sv,
           R"cue(		TITLE "Get Hard")cue"sv,
           R"cue(		PERFORMER "Hixxy & Re-Con")cue"sv,
           R"cue(		INDEX 01 48:32:00)cue"sv,
           R"cue(	TRACK 13 AUDIO)cue"sv,
           R"cue(		TITLE "Night Life (Hixxy Remix)")cue"sv,
           R"cue(		PERFORMER "Hixxy & Euphony Feat. Donna Marie")cue"sv,
           R"cue(		INDEX 01 52:09:00)cue"sv,
           R"cue(	TRACK 14 AUDIO)cue"sv,
           R"cue(		TITLE "I'm Hardcore, This Is What I Do")cue"sv,
           R"cue(		PERFORMER "Hixxy & Storm Meet Dougal & Gammer")cue"sv,
           R"cue(		INDEX 01 56:51:00)cue"sv,
           R"cue(	TRACK 15 AUDIO)cue"sv,
           R"cue(		TITLE "Sacrifice")cue"sv,
           R"cue(		PERFORMER "Hixxy")cue"sv,
           R"cue(		INDEX 01 61:50:00)cue"sv,
       }}};

  test_cue_generation(cue);
}

TEST(CueGeneration, r1) {
  const std::array<std::vector<std::string_view>, 1> cue = {
      {{R"cue(REM GENRE Deep House)cue"sv,
        R"cue(REM DATE 1999)cue"sv,
        R"cue(REM COMMENT "DCue v1.2dev")cue"sv,
        R"cue(PERFORMER "The Persuader")cue"sv,
        R"cue(TITLE "Stockholm")cue"sv,
        R"cue(FILE "r1.wav" WAVE)cue"sv,
        R"cue(	TRACK 01 AUDIO)cue"sv,
        R"cue(		TITLE "Östermalm")cue"sv,
        R"cue(		PERFORMER "The Persuader")cue"sv,
        R"cue(		INDEX 01 00:00:00)cue"sv,
        R"cue(	TRACK 02 AUDIO)cue"sv,
        R"cue(		TITLE "Vasastaden")cue"sv,
        R"cue(		PERFORMER "The Persuader")cue"sv,
        R"cue(		INDEX 01 04:45:00)cue"sv,
        R"cue(	TRACK 03 AUDIO)cue"sv,
        R"cue(		TITLE "Kungsholmen")cue"sv,
        R"cue(		PERFORMER "The Persuader")cue"sv,
        R"cue(		INDEX 01 10:56:00)cue"sv,
        R"cue(	TRACK 04 AUDIO)cue"sv,
        R"cue(		TITLE "Södermalm")cue"sv,
        R"cue(		PERFORMER "The Persuader")cue"sv,
        R"cue(		INDEX 01 13:45:00)cue"sv,
        R"cue(	TRACK 05 AUDIO)cue"sv,
        R"cue(		TITLE "Norrmalm")cue"sv,
        R"cue(		PERFORMER "The Persuader")cue"sv,
        R"cue(		INDEX 01 19:23:00)cue"sv,
        R"cue(	TRACK 06 AUDIO)cue"sv,
        R"cue(		TITLE "Gamla Stan")cue"sv,
        R"cue(		PERFORMER "The Persuader")cue"sv,
        R"cue(		INDEX 01 24:15:00)cue"sv}}};

  test_cue_generation(cue);
}

TEST(CueGeneration, r13835) {
  const std::array<std::vector<std::string_view>, 2> cue = {
      {{
           R"cue(REM GENRE Trance)cue"sv,
           R"cue(REM DATE 2000)cue"sv,
           R"cue(REM COMMENT "DCue v1.5dev")cue"sv,
           R"cue(PERFORMER "Ferry Corsten - System F")cue"sv,
           R"cue(TITLE "Trance Nation Four")cue"sv,
           R"cue(FILE "r13835.wav" WAVE)cue"sv,
           R"cue(	TRACK 01 AUDIO)cue"sv,
           R"cue(		TITLE "Kernkraft 400 (Original Mix)")cue"sv,
           R"cue(		PERFORMER "Zombie Nation")cue"sv,
           R"cue(		INDEX 01 00:00:00)cue"sv,
           R"cue(	TRACK 02 AUDIO)cue"sv,
           R"cue(		TITLE "Time To Burn (Original Mix)")cue"sv,
           R"cue(		PERFORMER "Storm")cue"sv,
           R"cue(		INDEX 01 03:26:00)cue"sv,
           R"cue(	TRACK 03 AUDIO)cue"sv,
           R"cue(		TITLE "Bullet In The Gun 2000 (Solar Stone Mix)")cue"sv,
           R"cue(		PERFORMER "Planet Perfecto")cue"sv,
           R"cue(		INDEX 01 06:24:00)cue"sv,
           R"cue(	TRACK 04 AUDIO)cue"sv,
           R"cue(		TITLE "Sandstorm (Original Mix)")cue"sv,
           R"cue(		PERFORMER "Darude")cue"sv,
           R"cue(		INDEX 01 10:31:00)cue"sv,
           R"cue(	TRACK 05 AUDIO)cue"sv,
           R"cue(		TITLE "Caned And Unable (Original Mix)")cue"sv,
           R"cue(		PERFORMER "Hi-Gate")cue"sv,
           R"cue(		INDEX 01 14:04:00)cue"sv,
           R"cue(	TRACK 06 AUDIO)cue"sv,
           R"cue(		TITLE "On The Beach (CRW Mix)")cue"sv,
           R"cue(		PERFORMER "York")cue"sv,
           R"cue(		INDEX 01 17:02:00)cue"sv,
           R"cue(	TRACK 07 AUDIO)cue"sv,
           R"cue(		TITLE "Two Tribes (Rob Searle Club Mix)")cue"sv,
           R"cue(		PERFORMER "Frankie Goes To Hollywood")cue"sv,
           R"cue(		INDEX 01 21:01:00)cue"sv,
           R"cue(	TRACK 08 AUDIO)cue"sv,
           R"cue(		TITLE "You Take My Breath Away (Lange Mix)")cue"sv,
           R"cue(		PERFORMER "SuReal")cue"sv,
           R"cue(		INDEX 01 26:41:00)cue"sv,
           R"cue(	TRACK 09 AUDIO)cue"sv,
           R"cue(		TITLE "Revelation (Ferry Corsten Remix)")cue"sv,
           R"cue(		PERFORMER "Electrique Boutique")cue"sv,
           R"cue(		INDEX 01 29:53:00)cue"sv,
           R"cue(	TRACK 10 AUDIO)cue"sv,
           R"cue(		TITLE "I Need Your Lovin' (Like The Sunshine) (Ferry Corsten Remix)")cue"sv,
           R"cue(		PERFORMER "Marc Et Claude")cue"sv,
           R"cue(		INDEX 01 33:19:00)cue"sv,
           R"cue(	TRACK 11 AUDIO)cue"sv,
           R"cue(		TITLE "Barber's Adagio For Strings (Ferry Corsten Remix)")cue"sv,
           R"cue(		PERFORMER "William Orbit")cue"sv,
           R"cue(		INDEX 01 37:52:00)cue"sv,
           R"cue(	TRACK 12 AUDIO)cue"sv,
           R"cue(		TITLE "Touch Me (Vocal Mix)")cue"sv,
           R"cue(		PERFORMER "Rising Star")cue"sv,
           R"cue(		INDEX 01 41:44:00)cue"sv,
           R"cue(	TRACK 13 AUDIO)cue"sv,
           R"cue(		TITLE "7 Colours (Angelic Remix)")cue"sv,
           R"cue(		PERFORMER "Lost Witness")cue"sv,
           R"cue(		INDEX 01 45:51:00)cue"sv,
           R"cue(	TRACK 14 AUDIO)cue"sv,
           R"cue(		TITLE "Far From Over (Oliver Lieb Remix)")cue"sv,
           R"cue(		PERFORMER "Kamaya Painters")cue"sv,
           R"cue(		INDEX 01 50:12:00)cue"sv,
           R"cue(	TRACK 15 AUDIO)cue"sv,
           R"cue(		TITLE "Truth (Original Mix)")cue"sv,
           R"cue(		PERFORMER "En-Motion")cue"sv,
           R"cue(		INDEX 01 54:06:00)cue"sv,
           R"cue(	TRACK 16 AUDIO)cue"sv,
           R"cue(		TITLE "Warrior (Club Mix)")cue"sv,
           R"cue(		PERFORMER "Warrior")cue"sv,
           R"cue(		INDEX 01 56:51:00)cue"sv,
           R"cue(	TRACK 17 AUDIO)cue"sv,
           R"cue(		TITLE "Bassfly (Moogwai Remix)")cue"sv,
           R"cue(		PERFORMER "Tillmann & Ries")cue"sv,
           R"cue(		INDEX 01 60:17:00)cue"sv,
           R"cue(	TRACK 18 AUDIO)cue"sv,
           R"cue(		TITLE "Bad Habit (Armin Van Buuren Rising Star Mix)")cue"sv,
           R"cue(		PERFORMER "A.T.F.C. Presents OnePhatDeeva Featuring Lisa Millett")cue"sv,
           R"cue(		INDEX 01 64:17:00)cue"sv,
           R"cue(	TRACK 19 AUDIO)cue"sv,
           R"cue(		TITLE "Isn't Life Wonderful? (Alex's Original Vocal Mix)")cue"sv,
           R"cue(		PERFORMER "Alex D'Elia vs Ebop Allstars")cue"sv,
           R"cue(		INDEX 01 68:52:00)cue"sv,
           R"cue(	TRACK 20 AUDIO)cue"sv,
           R"cue(		TITLE "Meet Us At Tonca (Choir Boys Remix)")cue"sv,
           R"cue(		PERFORMER "Tonca Boys")cue"sv,
           R"cue(		INDEX 01 72:35:00)cue"sv,
       },
       {
           R"cue(REM GENRE Trance)cue"sv,
           R"cue(REM DATE 2000)cue"sv,
           R"cue(REM COMMENT "DCue v1.5dev")cue"sv,
           R"cue(PERFORMER "Ferry Corsten - System F")cue"sv,
           R"cue(TITLE "Trance Nation Four")cue"sv,
           R"cue(FILE "r13835.wav" WAVE)cue"sv,
           R"cue(	TRACK 01 AUDIO)cue"sv,
           R"cue(		TITLE "Sexual (Deep Dish Cheez Whiz Dub)")cue"sv,
           R"cue(		PERFORMER "Amber")cue"sv,
           R"cue(		INDEX 01 00:00:00)cue"sv,
           R"cue(	TRACK 02 AUDIO)cue"sv,
           R"cue(		TITLE "How's Your Evening So Far? (UK 12'' Mix)")cue"sv,
           R"cue(		PERFORMER "Josh Wink & Lil Louis")cue"sv,
           R"cue(		INDEX 01 02:34:00)cue"sv,
           R"cue(	TRACK 03 AUDIO)cue"sv,
           R"cue(		TITLE "Silence (DJ Tiesto In Search Of Sunrise Remix)")cue"sv,
           R"cue(		PERFORMER "Delerium Featuring Sarah McLachlan")cue"sv,
           R"cue(		INDEX 01 07:55:00)cue"sv,
           R"cue(	TRACK 04 AUDIO)cue"sv,
           R"cue(		TITLE "Sister Sister (12'' Mix)")cue"sv,
           R"cue(		PERFORMER "Sister Bliss")cue"sv,
           R"cue(		INDEX 01 13:52:00)cue"sv,
           R"cue(	TRACK 05 AUDIO)cue"sv,
           R"cue(		TITLE "West On 27th (Original 'Subway' Mix)")cue"sv,
           R"cue(		PERFORMER "Killahurtz")cue"sv,
           R"cue(		INDEX 01 20:30:00)cue"sv,
           R"cue(	TRACK 06 AUDIO)cue"sv,
           R"cue(		TITLE "Impact (Original Mix)")cue"sv,
           R"cue(		PERFORMER "John Johnson")cue"sv,
           R"cue(		INDEX 01 24:41:00)cue"sv,
           R"cue(	TRACK 07 AUDIO)cue"sv,
           R"cue(		TITLE "Mauna Kea (Volcanic Mix)")cue"sv,
           R"cue(		PERFORMER "Twister")cue"sv,
           R"cue(		INDEX 01 29:06:00)cue"sv,
           R"cue(	TRACK 08 AUDIO)cue"sv,
           R"cue(		TITLE "Free (Mark Shimmon & 3rd Degree's Twister Remix)")cue"sv,
           R"cue(		PERFORMER "John '00' Fleming")cue"sv,
           R"cue(		INDEX 01 33:29:00)cue"sv,
           R"cue(	TRACK 09 AUDIO)cue"sv,
           R"cue(		TITLE "Lost In Motion (Original Mix)")cue"sv,
           R"cue(		PERFORMER "System F")cue"sv,
           R"cue(		INDEX 01 36:42:00)cue"sv,
           R"cue(	TRACK 10 AUDIO)cue"sv,
           R"cue(		TITLE "Skydive (Original Mix)")cue"sv,
           R"cue(		PERFORMER "Freefall Featuring Jan Johnston")cue"sv,
           R"cue(		INDEX 01 42:00:00)cue"sv,
           R"cue(	TRACK 11 AUDIO)cue"sv,
           R"cue(		TITLE "Love Has Come Again (Original Mix)")cue"sv,
           R"cue(		PERFORMER "Human Movement Featuring Sophie Moleta")cue"sv,
           R"cue(		INDEX 01 47:46:00)cue"sv,
           R"cue(	TRACK 12 AUDIO)cue"sv,
           R"cue(		TITLE "Desire (Dub Mix)")cue"sv,
           R"cue(		PERFORMER "Memnon Featuring Seroya")cue"sv,
           R"cue(		INDEX 01 51:42:00)cue"sv,
           R"cue(	TRACK 13 AUDIO)cue"sv,
           R"cue(		TITLE "Air 2000 (Oliver Lieb Remix)")cue"sv,
           R"cue(		PERFORMER "Albion")cue"sv,
           R"cue(		INDEX 01 55:10:00)cue"sv,
           R"cue(	TRACK 14 AUDIO)cue"sv,
           R"cue(		TITLE "Love Shy (Electrique Boutique Vocal Mix)")cue"sv,
           R"cue(		PERFORMER "Kristine Blond")cue"sv,
           R"cue(		INDEX 01 58:25:00)cue"sv,
           R"cue(	TRACK 15 AUDIO)cue"sv,
           R"cue(		TITLE "Fiji (Lange Remix)")cue"sv,
           R"cue(		PERFORMER "Atlantis vs Avatar Featuring Miriam Stockley")cue"sv,
           R"cue(		INDEX 01 62:21:00)cue"sv,
           R"cue(	TRACK 16 AUDIO)cue"sv,
           R"cue(		TITLE "Galaxia (Solar Stone Remix)")cue"sv,
           R"cue(		PERFORMER "Moonman")cue"sv,
           R"cue(		INDEX 01 66:47:00)cue"sv,
           R"cue(	TRACK 17 AUDIO)cue"sv,
           R"cue(		TITLE "Eternity (Darren Tate Mix)")cue"sv,
           R"cue(		PERFORMER "Orion")cue"sv,
           R"cue(		INDEX 01 71:53:00)cue"sv,
       }}};

  test_cue_generation(cue);
}

TEST(CueGeneration, r121788) {
  const std::array<std::vector<std::string_view>, 1> cue = {
      {{R"cue(REM GENRE Techno)cue"sv,
        R"cue(REM DATE 1995)cue"sv,
        R"cue(REM COMMENT "DCue v1.2dev")cue"sv,
        R"cue(PERFORMER "Mate Galic")cue"sv,
        R"cue(TITLE "The Original DJ Collection Vol. 1")cue"sv,
        R"cue(FILE "r121788.wav" WAVE)cue"sv,
        R"cue(	TRACK 01 AUDIO)cue"sv,
        R"cue(		TITLE "Why")cue"sv,
        R"cue(		PERFORMER "Rob Acid")cue"sv,
        R"cue(		INDEX 01 00:00:00)cue"sv,
        R"cue(	TRACK 02 AUDIO)cue"sv,
        R"cue(		TITLE "Sülk")cue"sv,
        R"cue(		PERFORMER "Encephaloid Disturbance")cue"sv,
        R"cue(		INDEX 01 04:11:00)cue"sv,
        R"cue(	TRACK 03 AUDIO)cue"sv,
        R"cue(		TITLE "Alphawave (Plasticman Acid House Mix)")cue"sv,
        R"cue(		PERFORMER "System 7")cue"sv,
        R"cue(		INDEX 01 07:44:00)cue"sv,
        R"cue(	TRACK 04 AUDIO)cue"sv,
        R"cue(		TITLE "Be Yourself (Original Mix)")cue"sv,
        R"cue(		PERFORMER "Rotor Type")cue"sv,
        R"cue(		INDEX 01 17:09:00)cue"sv,
        R"cue(	TRACK 05 AUDIO)cue"sv,
        R"cue(		TITLE "Acid Vol. 3")cue"sv,
        R"cue(		PERFORMER "Kox Box")cue"sv,
        R"cue(		INDEX 01 22:03:00)cue"sv,
        R"cue(	TRACK 06 AUDIO)cue"sv,
        R"cue(		TITLE "Brainworm")cue"sv,
        R"cue(		PERFORMER "Aural Traxx Vol. 1")cue"sv,
        R"cue(		INDEX 01 29:26:00)cue"sv,
        R"cue(	TRACK 07 AUDIO)cue"sv,
        R"cue(		TITLE "Space Bar")cue"sv,
        R"cue(		PERFORMER "Black Labs")cue"sv,
        R"cue(		INDEX 01 36:59:00)cue"sv,
        R"cue(	TRACK 08 AUDIO)cue"sv,
        R"cue(		TITLE "Gate 41")cue"sv,
        R"cue(		PERFORMER "The Source Expierience")cue"sv,
        R"cue(		INDEX 01 42:57:00)cue"sv,
        R"cue(	TRACK 09 AUDIO)cue"sv,
        R"cue(		TITLE "Fading Away")cue"sv,
        R"cue(		PERFORMER "Random XS")cue"sv,
        R"cue(		INDEX 01 50:33:00)cue"sv,
        R"cue(	TRACK 10 AUDIO)cue"sv,
        R"cue(		TITLE "Absolutely Lovely Stuff")cue"sv,
        R"cue(		PERFORMER "Sunrise")cue"sv,
        R"cue(		INDEX 01 56:42:00)cue"sv,
        R"cue(	TRACK 11 AUDIO)cue"sv,
        R"cue(		TITLE "Funalogue")cue"sv,
        R"cue(		PERFORMER "Hardfloor")cue"sv,
        R"cue(		INDEX 01 65:10:00)cue"sv,
        R"cue(	TRACK 12 AUDIO)cue"sv,
        R"cue(		TITLE "Kraj")cue"sv,
        R"cue(		PERFORMER "Notzucht")cue"sv,
        R"cue(		INDEX 01 71:40:00)cue"sv}}};

  test_cue_generation(cue);
}

TEST(CueGeneration, r374278) {
  const std::array<std::vector<std::string_view>, 1> cue = {
      {{R"cue(REM GENRE Psychedelic Rock)cue"sv,
        R"cue(REM DATE 1987)cue"sv,
        R"cue(REM COMMENT "DCue v1.5dev")cue"sv,
        R"cue(PERFORMER "Pink Floyd")cue"sv,
        R"cue(TITLE "Atom Heart Mother")cue"sv,
        R"cue(FILE "r374278.wav" WAVE)cue"sv,
        R"cue(	TRACK 01 AUDIO)cue"sv,
        R"cue(		TITLE "Atom Heart Mother")cue"sv,
        R"cue(		PERFORMER "Pink Floyd")cue"sv,
        R"cue(		INDEX 01 00:00:00)cue"sv,
        R"cue(	TRACK 02 AUDIO)cue"sv,
        R"cue(		TITLE "If")cue"sv,
        R"cue(		PERFORMER "Pink Floyd")cue"sv,
        R"cue(		INDEX 01 23:45:00)cue"sv,
        R"cue(	TRACK 03 AUDIO)cue"sv,
        R"cue(		TITLE "Summer '68")cue"sv,
        R"cue(		PERFORMER "Pink Floyd")cue"sv,
        R"cue(		INDEX 01 28:16:00)cue"sv,
        R"cue(	TRACK 04 AUDIO)cue"sv,
        R"cue(		TITLE "Fat Old Sun")cue"sv,
        R"cue(		PERFORMER "Pink Floyd")cue"sv,
        R"cue(		INDEX 01 33:44:00)cue"sv,
        R"cue(	TRACK 05 AUDIO)cue"sv,
        R"cue(		TITLE "Alan's Psychedelic Breakfast")cue"sv,
        R"cue(		PERFORMER "Pink Floyd")cue"sv,
        R"cue(		INDEX 01 39:07:00)cue"sv}

      }};

  test_cue_generation(cue);
}

TEST(CueGeneration, r3151795) {
  const std::array<std::vector<std::string_view>, 4> cue = {
      {{
           R"cue(REM GENRE Breakbeat)cue"sv,
           R"cue(REM DATE 2011)cue"sv,
           R"cue(REM COMMENT "DCue v1.4dev")cue"sv,
           R"cue(PERFORMER "Various")cue"sv,
           R"cue(TITLE "Hardcore Underground 5")cue"sv,
           R"cue(FILE "r3151795.wav" WAVE)cue"sv,
           R"cue(	TRACK 01 AUDIO)cue"sv,
           R"cue(		TITLE "Time Bomb (Al Storm Remix)")cue"sv,
           R"cue(		PERFORMER "CLSM Feat. Lisa Abbott")cue"sv,
           R"cue(		INDEX 01 00:00:00)cue"sv,
           R"cue(	TRACK 02 AUDIO)cue"sv,
           R"cue(		TITLE "Lights Down Low")cue"sv,
           R"cue(		PERFORMER "Technikore Feat. Jenny J")cue"sv,
           R"cue(		INDEX 01 03:12:00)cue"sv,
           R"cue(	TRACK 03 AUDIO)cue"sv,
           R"cue(		TITLE "Sheltered")cue"sv,
           R"cue(		PERFORMER "Al Storm, Technikore & JTS")cue"sv,
           R"cue(		INDEX 01 05:44:00)cue"sv,
           R"cue(	TRACK 04 AUDIO)cue"sv,
           R"cue(		TITLE "Hardcore Style")cue"sv,
           R"cue(		PERFORMER "Sy & Unknown")cue"sv,
           R"cue(		INDEX 01 08:27:00)cue"sv,
           R"cue(	TRACK 05 AUDIO)cue"sv,
           R"cue(		TITLE "All About Evolution")cue"sv,
           R"cue(		PERFORMER "Scott Brown & Al Storm")cue"sv,
           R"cue(		INDEX 01 09:42:00)cue"sv,
           R"cue(	TRACK 06 AUDIO)cue"sv,
           R"cue(		TITLE "The City Is Mine")cue"sv,
           R"cue(		PERFORMER "Sy & Technikore")cue"sv,
           R"cue(		INDEX 01 13:06:00)cue"sv,
           R"cue(	TRACK 07 AUDIO)cue"sv,
           R"cue(		TITLE "Get Ya Hands Up!")cue"sv,
           R"cue(		PERFORMER "Black & White Vs. Intraspekt & Outsider")cue"sv,
           R"cue(		INDEX 01 16:15:00)cue"sv,
           R"cue(	TRACK 08 AUDIO)cue"sv,
           R"cue(		TITLE "With Or Without You")cue"sv,
           R"cue(		PERFORMER "Unique")cue"sv,
           R"cue(		INDEX 01 18:02:00)cue"sv,
           R"cue(	TRACK 09 AUDIO)cue"sv,
           R"cue(		TITLE "Supersonik")cue"sv,
           R"cue(		PERFORMER "Technikore, JTS, Wain Johnstone & Kato")cue"sv,
           R"cue(		INDEX 01 20:11:00)cue"sv,
           R"cue(	TRACK 10 AUDIO)cue"sv,
           R"cue(		TITLE "So Much Stronger")cue"sv,
           R"cue(		PERFORMER "Al Storm Feat. Taya")cue"sv,
           R"cue(		INDEX 01 22:19:00)cue"sv,
           R"cue(	TRACK 11 AUDIO)cue"sv,
           R"cue(		TITLE "Euphoria")cue"sv,
           R"cue(		PERFORMER "Al Storm")cue"sv,
           R"cue(		INDEX 01 25:17:00)cue"sv,
           R"cue(	TRACK 12 AUDIO)cue"sv,
           R"cue(		TITLE "We'll Run Away")cue"sv,
           R"cue(		PERFORMER "Technikore & JTS Feat. Alan Booth")cue"sv,
           R"cue(		INDEX 01 28:29:00)cue"sv,
           R"cue(	TRACK 13 AUDIO)cue"sv,
           R"cue(		TITLE "Falling Out Of Love")cue"sv,
           R"cue(		PERFORMER "Fracus & Darwin Feat. Lisa Abbott")cue"sv,
           R"cue(		INDEX 01 32:43:00)cue"sv,
           R"cue(	TRACK 14 AUDIO)cue"sv,
           R"cue(		TITLE "Poltergeist")cue"sv,
           R"cue(		PERFORMER "Al Storm & MOB")cue"sv,
           R"cue(		INDEX 01 36:06:00)cue"sv,
           R"cue(	TRACK 15 AUDIO)cue"sv,
           R"cue(		TITLE "Feel The Power (Technikore Remix)")cue"sv,
           R"cue(		PERFORMER "Breeze & Styles")cue"sv,
           R"cue(		INDEX 01 38:01:00)cue"sv,
           R"cue(	TRACK 16 AUDIO)cue"sv,
           R"cue(		TITLE "Give A Little Bit Of Love")cue"sv,
           R"cue(		PERFORMER "Al Storm & Euphony Feat. Vicky Fee")cue"sv,
           R"cue(		INDEX 01 41:37:00)cue"sv,
           R"cue(	TRACK 17 AUDIO)cue"sv,
           R"cue(		TITLE "This Is How It's Done")cue"sv,
           R"cue(		PERFORMER "Technikore, Al Storm & JTS")cue"sv,
           R"cue(		INDEX 01 44:48:00)cue"sv,
           R"cue(	TRACK 18 AUDIO)cue"sv,
           R"cue(		TITLE "Betrayed (Winter Stayed)")cue"sv,
           R"cue(		PERFORMER "Technikore & Minty Feat. Nathalie")cue"sv,
           R"cue(		INDEX 01 47:05:00)cue"sv,
           R"cue(	TRACK 19 AUDIO)cue"sv,
           R"cue(		TITLE "The Fly (VIP Mix)")cue"sv,
           R"cue(		PERFORMER "Sy & Technikore")cue"sv,
           R"cue(		INDEX 01 51:18:00)cue"sv,
           R"cue(	TRACK 20 AUDIO)cue"sv,
           R"cue(		TITLE "Al Storm's Essential Mega-Muffin (Feat. MC Whizzkid)")cue"sv,
           R"cue(		PERFORMER "Dougal & Gammer")cue"sv,
           R"cue(		INDEX 01 53:46:00)cue"sv,
           R"cue(	TRACK 21 AUDIO)cue"sv,
           R"cue(		TITLE "Run To Me")cue"sv,
           R"cue(		PERFORMER "Al Storm Vs. Plus System Feat. Taya")cue"sv,
           R"cue(		INDEX 01 57:13:00)cue"sv,
           R"cue(	TRACK 22 AUDIO)cue"sv,
           R"cue(		TITLE "Step Down")cue"sv,
           R"cue(		PERFORMER "Fracus & Darwin")cue"sv,
           R"cue(		INDEX 01 59:33:00)cue"sv,
           R"cue(	TRACK 23 AUDIO)cue"sv,
           R"cue(		TITLE "Somebody")cue"sv,
           R"cue(		PERFORMER "Technikore")cue"sv,
           R"cue(		INDEX 01 61:30:00)cue"sv,
           R"cue(	TRACK 24 AUDIO)cue"sv,
           R"cue(		TITLE "Lonely (Abused Mix)")cue"sv,
           R"cue(		PERFORMER "Sy & Al Storm Feat. Meri Everitt")cue"sv,
           R"cue(		INDEX 01 64:07:00)cue"sv,
           R"cue(	TRACK 25 AUDIO)cue"sv,
           R"cue(		TITLE "Hardcore 2 The Bone!")cue"sv,
           R"cue(		PERFORMER "Al Storm")cue"sv,
           R"cue(		INDEX 01 66:38:00)cue"sv,
           R"cue(	TRACK 26 AUDIO)cue"sv,
           R"cue(		TITLE "Rock Me Out (Al Storm & Technikore's Chopper Mix)")cue"sv,
           R"cue(		PERFORMER "Darren Styles")cue"sv,
           R"cue(		INDEX 01 68:47:00)cue"sv,
           R"cue(	TRACK 27 AUDIO)cue"sv,
           R"cue(		TITLE "The Nerve Centre")cue"sv,
           R"cue(		PERFORMER "Sy & Technikore")cue"sv,
           R"cue(		INDEX 01 71:39:00)cue"sv,
           R"cue(	TRACK 28 AUDIO)cue"sv,
           R"cue(		TITLE "Payback")cue"sv,
           R"cue(		PERFORMER "Technikore & JTS")cue"sv,
           R"cue(		INDEX 01 73:37:00)cue"sv,
       },
       {
           R"cue(REM GENRE Breakbeat)cue"sv,
           R"cue(REM DATE 2011)cue"sv,
           R"cue(REM COMMENT "DCue v1.4dev")cue"sv,
           R"cue(PERFORMER "Various")cue"sv,
           R"cue(TITLE "Hardcore Underground 5")cue"sv,
           R"cue(FILE "r3151795.wav" WAVE)cue"sv,
           R"cue(	TRACK 01 AUDIO)cue"sv,
           R"cue(		TITLE "Can You Hear The Silence")cue"sv,
           R"cue(		PERFORMER "Entity & Chwhynny")cue"sv,
           R"cue(		INDEX 01 00:00:00)cue"sv,
           R"cue(	TRACK 02 AUDIO)cue"sv,
           R"cue(		TITLE "Chime")cue"sv,
           R"cue(		PERFORMER "Fracus & Darwin Vs. CLSM Feat. Indie-Go Blue")cue"sv,
           R"cue(		INDEX 01 02:05:00)cue"sv,
           R"cue(	TRACK 03 AUDIO)cue"sv,
           R"cue(		TITLE "Burning Up")cue"sv,
           R"cue(		PERFORMER "Sam B")cue"sv,
           R"cue(		INDEX 01 04:48:00)cue"sv,
           R"cue(	TRACK 04 AUDIO)cue"sv,
           R"cue(		TITLE "Ganja Crew")cue"sv,
           R"cue(		PERFORMER "Fracus & Darwin")cue"sv,
           R"cue(		INDEX 01 06:58:00)cue"sv,
           R"cue(	TRACK 05 AUDIO)cue"sv,
           R"cue(		TITLE "Got The Rhythm")cue"sv,
           R"cue(		PERFORMER "Fracus & Darwin Feat. Becca Hossany")cue"sv,
           R"cue(		INDEX 01 08:25:00)cue"sv,
           R"cue(	TRACK 06 AUDIO)cue"sv,
           R"cue(		TITLE "Movin' To This")cue"sv,
           R"cue(		PERFORMER "JAKAZiD")cue"sv,
           R"cue(		INDEX 01 12:25:00)cue"sv,
           R"cue(	TRACK 07 AUDIO)cue"sv,
           R"cue(		TITLE "My Heartbeat")cue"sv,
           R"cue(		PERFORMER "Brisk & Darwin Vs. DMO")cue"sv,
           R"cue(		INDEX 01 17:08:00)cue"sv,
           R"cue(	TRACK 08 AUDIO)cue"sv,
           R"cue(		TITLE "Madjik")cue"sv,
           R"cue(		PERFORMER "Fracus")cue"sv,
           R"cue(		INDEX 01 21:19:00)cue"sv,
           R"cue(	TRACK 09 AUDIO)cue"sv,
           R"cue(		TITLE "Hypnotic")cue"sv,
           R"cue(		PERFORMER "Fracus & Darwin Feat. Becca Hossany")cue"sv,
           R"cue(		INDEX 01 24:51:00)cue"sv,
           R"cue(	TRACK 10 AUDIO)cue"sv,
           R"cue(		TITLE "Lose You Again")cue"sv,
           R"cue(		PERFORMER "Brooklyn & Dan Edge")cue"sv,
           R"cue(		INDEX 01 27:45:00)cue"sv,
           R"cue(	TRACK 11 AUDIO)cue"sv,
           R"cue(		TITLE "Route 143 (TANUKI Remix)")cue"sv,
           R"cue(		PERFORMER "M-Project")cue"sv,
           R"cue(		INDEX 01 29:55:00)cue"sv,
           R"cue(	TRACK 12 AUDIO)cue"sv,
           R"cue(		TITLE "Goodbye (Fracus & Darwin Remix)")cue"sv,
           R"cue(		PERFORMER "Buzz & Stevie D Feat. Jessica Palmer")cue"sv,
           R"cue(		INDEX 01 32:03:00)cue"sv,
           R"cue(	TRACK 13 AUDIO)cue"sv,
           R"cue(		TITLE "Blessed Loneliness")cue"sv,
           R"cue(		PERFORMER "Daniel Seven")cue"sv,
           R"cue(		INDEX 01 36:31:00)cue"sv,
           R"cue(	TRACK 14 AUDIO)cue"sv,
           R"cue(		TITLE "Shouting Out (Fracus & Darwin Remix)")cue"sv,
           R"cue(		PERFORMER "Brisk & Vagabond")cue"sv,
           R"cue(		INDEX 01 38:39:00)cue"sv,
           R"cue(	TRACK 15 AUDIO)cue"sv,
           R"cue(		TITLE "The New Style")cue"sv,
           R"cue(		PERFORMER "Bishop & Tom Revolution")cue"sv,
           R"cue(		INDEX 01 40:37:00)cue"sv,
           R"cue(	TRACK 16 AUDIO)cue"sv,
           R"cue(		TITLE "Love Sick Crazy (Fracus & Darwin Remix)")cue"sv,
           R"cue(		PERFORMER "Styles & Breeze Feat. Recon")cue"sv,
           R"cue(		INDEX 01 41:50:00)cue"sv,
           R"cue(	TRACK 17 AUDIO)cue"sv,
           R"cue(		TITLE "Life's A Journey")cue"sv,
           R"cue(		PERFORMER "Brisk & Darwin Feat. Taya")cue"sv,
           R"cue(		INDEX 01 44:52:00)cue"sv,
           R"cue(	TRACK 18 AUDIO)cue"sv,
           R"cue(		TITLE "Falling Into You")cue"sv,
           R"cue(		PERFORMER "Brisk & Fracus")cue"sv,
           R"cue(		INDEX 01 49:01:00)cue"sv,
           R"cue(	TRACK 19 AUDIO)cue"sv,
           R"cue(		TITLE "Break The Concrete")cue"sv,
           R"cue(		PERFORMER "Brisk & Darwin")cue"sv,
           R"cue(		INDEX 01 52:03:00)cue"sv,
           R"cue(	TRACK 20 AUDIO)cue"sv,
           R"cue(		TITLE "Radio Rockin' 2011")cue"sv,
           R"cue(		PERFORMER "Brisk & Fracus")cue"sv,
           R"cue(		INDEX 01 54:43:00)cue"sv,
           R"cue(	TRACK 21 AUDIO)cue"sv,
           R"cue(		TITLE "Sex Toys")cue"sv,
           R"cue(		PERFORMER "Brisk & Ham")cue"sv,
           R"cue(		INDEX 01 57:59:00)cue"sv,
           R"cue(	TRACK 22 AUDIO)cue"sv,
           R"cue(		TITLE "Bulletproof")cue"sv,
           R"cue(		PERFORMER "Double Dutch")cue"sv,
           R"cue(		INDEX 01 59:56:00)cue"sv,
           R"cue(	TRACK 23 AUDIO)cue"sv,
           R"cue(		TITLE "I'm Not An Addict (Brisk Remix)")cue"sv,
           R"cue(		PERFORMER "Paul Elstak Feat. Beatstream & Radiate")cue"sv,
           R"cue(		INDEX 01 62:23:00)cue"sv,
           R"cue(	TRACK 24 AUDIO)cue"sv,
           R"cue(		TITLE "God's Fury")cue"sv,
           R"cue(		PERFORMER "Art Of Fighters")cue"sv,
           R"cue(		INDEX 01 65:59:00)cue"sv,
           R"cue(	TRACK 25 AUDIO)cue"sv,
           R"cue(		TITLE "Snitcher!")cue"sv,
           R"cue(		PERFORMER "Neophyte & Tha Playah")cue"sv,
           R"cue(		INDEX 01 67:49:00)cue"sv,
           R"cue(	TRACK 26 AUDIO)cue"sv,
           R"cue(		TITLE "Pitch Black (Kasparov Remix)")cue"sv,
           R"cue(		PERFORMER "Kasparov")cue"sv,
           R"cue(		INDEX 01 69:55:00)cue"sv,
       },
       {
           R"cue(REM GENRE Breakbeat)cue"sv,
           R"cue(REM DATE 2011)cue"sv,
           R"cue(REM COMMENT "DCue v1.4dev")cue"sv,
           R"cue(PERFORMER "Various")cue"sv,
           R"cue(TITLE "Hardcore Underground 5")cue"sv,
           R"cue(FILE "r3151795.wav" WAVE)cue"sv,
           R"cue(	TRACK 01 AUDIO)cue"sv,
           R"cue(		TITLE "Sky")cue"sv,
           R"cue(		PERFORMER "Gavin G")cue"sv,
           R"cue(		INDEX 01 00:00:00)cue"sv,
           R"cue(	TRACK 02 AUDIO)cue"sv,
           R"cue(		TITLE "Petrichor")cue"sv,
           R"cue(		PERFORMER "StrifeII")cue"sv,
           R"cue(		INDEX 01 03:05:00)cue"sv,
           R"cue(	TRACK 03 AUDIO)cue"sv,
           R"cue(		TITLE "Energize (Renegade Slammer)")cue"sv,
           R"cue(		PERFORMER "Shimamura")cue"sv,
           R"cue(		INDEX 01 04:32:00)cue"sv,
           R"cue(	TRACK 04 AUDIO)cue"sv,
           R"cue(		TITLE "No Disguise")cue"sv,
           R"cue(		PERFORMER "Fracus & Darwin")cue"sv,
           R"cue(		INDEX 01 07:26:00)cue"sv,
           R"cue(	TRACK 05 AUDIO)cue"sv,
           R"cue(		TITLE "A Touch Of Magic (Uplift & Stargazer 2011 Remix)")cue"sv,
           R"cue(		PERFORMER "Kingsize & Eternity")cue"sv,
           R"cue(		INDEX 01 09:36:00)cue"sv,
           R"cue(	TRACK 06 AUDIO)cue"sv,
           R"cue(		TITLE "I Will Wait (Fracus & Darwin Remix)")cue"sv,
           R"cue(		PERFORMER "CLSM")cue"sv,
           R"cue(		INDEX 01 12:52:00)cue"sv,
           R"cue(	TRACK 07 AUDIO)cue"sv,
           R"cue(		TITLE "Summer")cue"sv,
           R"cue(		PERFORMER "Samba D")cue"sv,
           R"cue(		INDEX 01 15:46:00)cue"sv,
           R"cue(	TRACK 08 AUDIO)cue"sv,
           R"cue(		TITLE "You're Driving Me Crazy")cue"sv,
           R"cue(		PERFORMER "Chris Ross & Audioshift")cue"sv,
           R"cue(		INDEX 01 19:30:00)cue"sv,
           R"cue(	TRACK 09 AUDIO)cue"sv,
           R"cue(		TITLE "Can't Get Enough")cue"sv,
           R"cue(		PERFORMER "Entity & Sam B")cue"sv,
           R"cue(		INDEX 01 22:24:00)cue"sv,
           R"cue(	TRACK 10 AUDIO)cue"sv,
           R"cue(		TITLE "Shape Of Love")cue"sv,
           R"cue(		PERFORMER "Darwin & Koopa Vs. Phenex Feat. Le Kat")cue"sv,
           R"cue(		INDEX 01 25:18:00)cue"sv,
           R"cue(	TRACK 11 AUDIO)cue"sv,
           R"cue(		TITLE "Acid Porn Monkey")cue"sv,
           R"cue(		PERFORMER "Sc@r")cue"sv,
           R"cue(		INDEX 01 28:12:00)cue"sv,
           R"cue(	TRACK 12 AUDIO)cue"sv,
           R"cue(		TITLE "Only For Me")cue"sv,
           R"cue(		PERFORMER "Slipmatt & Darwin")cue"sv,
           R"cue(		INDEX 01 31:17:00)cue"sv,
           R"cue(	TRACK 13 AUDIO)cue"sv,
           R"cue(		TITLE "Love Obsession (SMD Remix)")cue"sv,
           R"cue(		PERFORMER "Fracus & Darwin Feat. Cat Knight")cue"sv,
           R"cue(		INDEX 01 33:52:00)cue"sv,
           R"cue(	TRACK 14 AUDIO)cue"sv,
           R"cue(		TITLE "Falling Through (CLSM Remix)")cue"sv,
           R"cue(		PERFORMER "Al Storm & The Acolyte Feat. Lisa Abbott")cue"sv,
           R"cue(		INDEX 01 36:57:00)cue"sv,
           R"cue(	TRACK 15 AUDIO)cue"sv,
           R"cue(		TITLE "Hollow")cue"sv,
           R"cue(		PERFORMER "TANUKI")cue"sv,
           R"cue(		INDEX 01 40:02:00)cue"sv,
           R"cue(	TRACK 16 AUDIO)cue"sv,
           R"cue(		TITLE "Feel So High (No Left Turn Remix)")cue"sv,
           R"cue(		PERFORMER "Dain-Ja Feat. Vicky Fee")cue"sv,
           R"cue(		INDEX 01 43:40:00)cue"sv,
           R"cue(	TRACK 17 AUDIO)cue"sv,
           R"cue(		TITLE "Dream Of The Moment")cue"sv,
           R"cue(		PERFORMER "Fracus & In Effect Feat. Sam Honey")cue"sv,
           R"cue(		INDEX 01 45:54:00)cue"sv,
           R"cue(	TRACK 18 AUDIO)cue"sv,
           R"cue(		TITLE "Irish Sunrise")cue"sv,
           R"cue(		PERFORMER "Raving Donkey")cue"sv,
           R"cue(		INDEX 01 48:25:00)cue"sv,
           R"cue(	TRACK 19 AUDIO)cue"sv,
           R"cue(		TITLE "Sunflower (Sam B Remix)")cue"sv,
           R"cue(		PERFORMER "Firefly")cue"sv,
           R"cue(		INDEX 01 51:41:00)cue"sv,
           R"cue(	TRACK 20 AUDIO)cue"sv,
           R"cue(		TITLE "Waves Of Desire (Karl Future's Hardcore Junglist Remix)")cue"sv,
           R"cue(		PERFORMER "Kevin Energy")cue"sv,
           R"cue(		INDEX 01 54:37:00)cue"sv,
           R"cue(	TRACK 21 AUDIO)cue"sv,
           R"cue(		TITLE "Wake Up Call")cue"sv,
           R"cue(		PERFORMER "Fracus & Tom Revolution")cue"sv,
           R"cue(		INDEX 01 58:18:00)cue"sv,
           R"cue(	TRACK 22 AUDIO)cue"sv,
           R"cue(		TITLE "Dust (Pulse Remix)")cue"sv,
           R"cue(		PERFORMER "Ultravibes")cue"sv,
           R"cue(		INDEX 01 61:13:00)cue"sv,
           R"cue(	TRACK 23 AUDIO)cue"sv,
           R"cue(		TITLE "Did You See It")cue"sv,
           R"cue(		PERFORMER "Entity")cue"sv,
           R"cue(		INDEX 01 63:22:00)cue"sv,
           R"cue(	TRACK 24 AUDIO)cue"sv,
           R"cue(		TITLE "One & Only")cue"sv,
           R"cue(		PERFORMER "Ham")cue"sv,
           R"cue(		INDEX 01 66:47:00)cue"sv,
           R"cue(	TRACK 25 AUDIO)cue"sv,
           R"cue(		TITLE "21 Days")cue"sv,
           R"cue(		PERFORMER "Entity & Darwin Feat. MC Sharkey")cue"sv,
           R"cue(		INDEX 01 69:16:00)cue"sv,
           R"cue(	TRACK 26 AUDIO)cue"sv,
           R"cue(		TITLE "Stay With Me (Darwin Remix)")cue"sv,
           R"cue(		PERFORMER "DJ Demand")cue"sv,
           R"cue(		INDEX 01 72:22:00)cue"sv,
           R"cue(	TRACK 27 AUDIO)cue"sv,
           R"cue(		TITLE "Every Time (‘90s Revival Mix)")cue"sv,
           R"cue(		PERFORMER "Brisk & Darwin")cue"sv,
           R"cue(		INDEX 01 74:40:00)cue"sv,
       },
       {
           R"cue(REM GENRE Breakbeat)cue"sv,
           R"cue(REM DATE 2011)cue"sv,
           R"cue(REM COMMENT "DCue v1.4dev")cue"sv,
           R"cue(PERFORMER "Various")cue"sv,
           R"cue(TITLE "Hardcore Underground 5")cue"sv,
           R"cue(FILE "r3151795.wav" WAVE)cue"sv,
           R"cue(	TRACK 01 AUDIO)cue"sv,
           R"cue(		TITLE "NanEater (HU Intro Mix Feat. Dark Angel)")cue"sv,
           R"cue(		PERFORMER "A.B & Solution")cue"sv,
           R"cue(		INDEX 01 00:00:00)cue"sv,
           R"cue(	TRACK 02 AUDIO)cue"sv,
           R"cue(		TITLE "Genre This!")cue"sv,
           R"cue(		PERFORMER "A.B & SynthWulf")cue"sv,
           R"cue(		INDEX 01 03:52:00)cue"sv,
           R"cue(	TRACK 03 AUDIO)cue"sv,
           R"cue(		TITLE "Weekend")cue"sv,
           R"cue(		PERFORMER "Haywire")cue"sv,
           R"cue(		INDEX 01 06:19:00)cue"sv,
           R"cue(	TRACK 04 AUDIO)cue"sv,
           R"cue(		TITLE "Future Skool")cue"sv,
           R"cue(		PERFORMER "Pinnacle & Ben Av-It")cue"sv,
           R"cue(		INDEX 01 08:46:00)cue"sv,
           R"cue(	TRACK 05 AUDIO)cue"sv,
           R"cue(		TITLE "Stay With Me (Greg Peaks Remix)")cue"sv,
           R"cue(		PERFORMER "A.B")cue"sv,
           R"cue(		INDEX 01 11:04:00)cue"sv,
           R"cue(	TRACK 06 AUDIO)cue"sv,
           R"cue(		TITLE "Show Me Love (Deeper Territory Remix)")cue"sv,
           R"cue(		PERFORMER "Darts Feat. Kelly C")cue"sv,
           R"cue(		INDEX 01 13:52:00)cue"sv,
           R"cue(	TRACK 07 AUDIO)cue"sv,
           R"cue(		TITLE "The Prophet")cue"sv,
           R"cue(		PERFORMER "Endemic")cue"sv,
           R"cue(		INDEX 01 15:37:00)cue"sv,
           R"cue(	TRACK 08 AUDIO)cue"sv,
           R"cue(		TITLE "State Of Life")cue"sv,
           R"cue(		PERFORMER "Kevin Energy & Rik Arkitech Feat. Rhona")cue"sv,
           R"cue(		INDEX 01 17:06:00)cue"sv,
           R"cue(	TRACK 09 AUDIO)cue"sv,
           R"cue(		TITLE "Air")cue"sv,
           R"cue(		PERFORMER "Douglas Feat. Dionne")cue"sv,
           R"cue(		INDEX 01 21:39:00)cue"sv,
           R"cue(	TRACK 10 AUDIO)cue"sv,
           R"cue(		TITLE "Without You (Cube::Hard Remix)")cue"sv,
           R"cue(		PERFORMER "X-Cyte Feat. Freda")cue"sv,
           R"cue(		INDEX 01 24:57:00)cue"sv,
           R"cue(	TRACK 11 AUDIO)cue"sv,
           R"cue(		TITLE "Beyond Us (Douglas Remix)")cue"sv,
           R"cue(		PERFORMER "Rampant, Obie & Darwin")cue"sv,
           R"cue(		INDEX 01 28:09:00)cue"sv,
           R"cue(	TRACK 12 AUDIO)cue"sv,
           R"cue(		TITLE "Codex")cue"sv,
           R"cue(		PERFORMER "Cube::Hard & Douglas")cue"sv,
           R"cue(		INDEX 01 31:02:00)cue"sv,
           R"cue(	TRACK 13 AUDIO)cue"sv,
           R"cue(		TITLE "Sin 4 Me (A.B's Trouse Remix)")cue"sv,
           R"cue(		PERFORMER "Kevin Energy & A.B")cue"sv,
           R"cue(		INDEX 01 34:24:00)cue"sv,
           R"cue(	TRACK 14 AUDIO)cue"sv,
           R"cue(		TITLE "Warlock (Cube::Hard Remix)")cue"sv,
           R"cue(		PERFORMER "Lost Soul")cue"sv,
           R"cue(		INDEX 01 38:32:00)cue"sv,
           R"cue(	TRACK 15 AUDIO)cue"sv,
           R"cue(		TITLE "Investatron 3000")cue"sv,
           R"cue(		PERFORMER "Endemic")cue"sv,
           R"cue(		INDEX 01 41:01:00)cue"sv,
           R"cue(	TRACK 16 AUDIO)cue"sv,
           R"cue(		TITLE "Beaker Face")cue"sv,
           R"cue(		PERFORMER "Firefarm & Kevin Energy")cue"sv,
           R"cue(		INDEX 01 43:54:00)cue"sv,
           R"cue(	TRACK 17 AUDIO)cue"sv,
           R"cue(		TITLE "Domination")cue"sv,
           R"cue(		PERFORMER "Transcend")cue"sv,
           R"cue(		INDEX 01 47:22:00)cue"sv,
           R"cue(	TRACK 18 AUDIO)cue"sv,
           R"cue(		TITLE "Disorder")cue"sv,
           R"cue(		PERFORMER "Douglas & Remane")cue"sv,
           R"cue(		INDEX 01 50:11:00)cue"sv,
           R"cue(	TRACK 19 AUDIO)cue"sv,
           R"cue(		TITLE "Zero-G Fire")cue"sv,
           R"cue(		PERFORMER "Transcend")cue"sv,
           R"cue(		INDEX 01 54:11:00)cue"sv,
           R"cue(	TRACK 20 AUDIO)cue"sv,
           R"cue(		TITLE "Solas An Lae (Douglas HU5 Remix)")cue"sv,
           R"cue(		PERFORMER "Andy Dee")cue"sv,
           R"cue(		INDEX 01 56:43:00)cue"sv,
           R"cue(	TRACK 21 AUDIO)cue"sv,
           R"cue(		TITLE "Escapia")cue"sv,
           R"cue(		PERFORMER "A.B")cue"sv,
           R"cue(		INDEX 01 61:28:00)cue"sv,
           R"cue(	TRACK 22 AUDIO)cue"sv,
           R"cue(		TITLE "False Religion")cue"sv,
           R"cue(		PERFORMER "Rik Arkitech & Douglas")cue"sv,
           R"cue(		INDEX 01 63:21:00)cue"sv,
           R"cue(	TRACK 23 AUDIO)cue"sv,
           R"cue(		TITLE "Reform Your Freeform")cue"sv,
           R"cue(		PERFORMER "Kevin Energy & A.B")cue"sv,
           R"cue(		INDEX 01 66:34:00)cue"sv,
           R"cue(	TRACK 24 AUDIO)cue"sv,
           R"cue(		TITLE "Fin")cue"sv,
           R"cue(		PERFORMER "A.B & Douglas")cue"sv,
           R"cue(		INDEX 01 70:06:00)cue"sv,
       }}};
  test_cue_generation(cue);
}

TEST(CueGeneration, r9922074) {
  const std::array<std::vector<std::string_view>, 1> cue = {{{
      R"cue(REM GENRE Eurobeat)cue"sv,
      R"cue(REM DATE 2016)cue"sv,
      R"cue(REM COMMENT "DCue v1.4dev")cue"sv,
      R"cue(PERFORMER "Various")cue"sv,
      R"cue(TITLE "Eurobeat Festival Vol. 2")cue"sv,
      R"cue(FILE "r9922074.wav" WAVE)cue"sv,
      R"cue(	TRACK 01 AUDIO)cue"sv,
      R"cue(		TITLE "Everlasting")cue"sv,
      R"cue(		PERFORMER "Shironegi")cue"sv,
      R"cue(		INDEX 01 00:00:00)cue"sv,
      R"cue(	TRACK 02 AUDIO)cue"sv,
      R"cue(		TITLE "Boom Boom Lovin' Desire")cue"sv,
      R"cue(		PERFORMER "紅梔子")cue"sv,
      R"cue(		INDEX 01 05:24:00)cue"sv,
      R"cue(	TRACK 03 AUDIO)cue"sv,
      R"cue(		TITLE "Dear Mr.Heartbreaker")cue"sv,
      R"cue(		PERFORMER "Rin")cue"sv,
      R"cue(		INDEX 01 09:52:00)cue"sv,
      R"cue(	TRACK 04 AUDIO)cue"sv,
      R"cue(		TITLE "バグズ・ナイト")cue"sv,
      R"cue(		PERFORMER "紅梔子")cue"sv,
      R"cue(		INDEX 01 14:44:00)cue"sv,
      R"cue(	TRACK 05 AUDIO)cue"sv,
      R"cue(		TITLE "Midnight Shot!! 2016")cue"sv,
      R"cue(		PERFORMER "紅梔子 & ノイズ")cue"sv,
      R"cue(		INDEX 01 19:36:00)cue"sv,
      R"cue(	TRACK 06 AUDIO)cue"sv,
      R"cue(		TITLE "Eurobeat Ninja Comes Again")cue"sv,
      R"cue(		PERFORMER "nmk")cue"sv,
      R"cue(		INDEX 01 24:28:00)cue"sv,
      R"cue(	TRACK 07 AUDIO)cue"sv,
      R"cue(		TITLE "Oblivion Phantasm")cue"sv,
      R"cue(		PERFORMER "Setuna")cue"sv,
      R"cue(		INDEX 01 28:32:00)cue"sv,
      R"cue(	TRACK 08 AUDIO)cue"sv,
      R"cue(		TITLE "Real Hero (Haseko × Sato. Edit)")cue"sv,
      R"cue(		PERFORMER "紅梔子")cue"sv,
      R"cue(		INDEX 01 32:43:00)cue"sv,
      R"cue(	TRACK 09 AUDIO)cue"sv,
      R"cue(		TITLE "Sadness Memory")cue"sv,
      R"cue(		PERFORMER "橘花音")cue"sv,
      R"cue(		INDEX 01 39:05:00)cue"sv,
      R"cue(	TRACK 10 AUDIO)cue"sv,
      R"cue(		TITLE "Peerless Gale")cue"sv,
      R"cue(		PERFORMER "かなえゆめ")cue"sv,
      R"cue(		INDEX 01 43:07:00)cue"sv,
      R"cue(	TRACK 11 AUDIO)cue"sv,
      R"cue(		TITLE "Midnight Shot!! 2016 (Instrumental)")cue"sv,
      R"cue(		PERFORMER "Sugano")cue"sv,
      R"cue(		INDEX 01 47:45:00)cue"sv,
      R"cue(	TRACK 12 AUDIO)cue"sv,
      R"cue(		TITLE "Eurobeat Ninja Comes Again (Instrumental)")cue"sv,
      R"cue(		PERFORMER "nmk")cue"sv,
      R"cue(		INDEX 01 52:37:00)cue"sv,
      R"cue(	TRACK 13 AUDIO)cue"sv,
      R"cue(		TITLE "Oblivion Phantasm (Instrumental)")cue"sv,
      R"cue(		PERFORMER "Haseko")cue"sv,
      R"cue(		INDEX 01 56:39:00)cue"sv,
  }}};
  test_cue_generation(cue);
}
