name: Official build - Linux

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-lnx:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install curl
      run: sudo apt-get update && sudo apt-get install libcurl4-openssl-dev ninja-build

    - name: Build
      env:
        DCUE_APP_KEY: ${{ secrets.DCUE_APP_KEY }}
        DCUE_APP_SECRET: ${{ secrets.DCUE_APP_SECRET }}
        DCUE_APP_XORKEY: ${{ secrets.DCUE_APP_XORKEY }}
      run: .github/lnx_official.sh

    - uses: actions/upload-artifact@v2
      with:
        name: DCue for Linux
        path: build/dcue-lnx-x86_64.AppImage
      name: upload-dcue-build
